---
title: "Unwholesome Consciousness and Stress"
author: "Edward Hillenaar"
date: "2023-07-31"
output: html_document
---



<div id="abstract" class="section level1">
<h1><strong>Abstract</strong></h1>
<p>This scientific article investigates the relationship between consciousness and stress, with a specific focus on “unwholesome” consciousness and its potential role as a predictor of depression. The study utilizes data from the Nederlandse Verkorte MMPI (NVM) in a dataset encompassing various characteristics related to consciousness and mental stress. Through regression analysis, odds ratios are estimated to quantify the strength of the association between consciousness and depression. The results show a significant link between unwholesome consciousness and depression, indicating that negative valence plays a key role in susceptibility to stress-related mental health issues. Furthermore, the visualization of behavior factors based on consciousness categories provides additional insights into their impact on stress outcomes. The study also explores the influence of gender on consciousness levels in relation to stress, revealing a universal relationship between unwholesome consciousness and depression across genders. The findings contribute to stress management and mental well-being interventions, emphasizing the importance of addressing unwholesome consciousness to promote positive cognitive patterns and emotional well-being. Understanding the diverse pathways between consciousness and stress helps develop effective strategies for mental health.</p>
<p><strong>Keywords</strong>: Unwholesome Consciousness, Stress, Depression, Nederlandse Verkorte MMPI, Regression Analysis, Odds Ratio</p>
</div>
<div id="introduction" class="section level1">
<h1><strong>Introduction</strong></h1>
<p>In recent years, stress and its impact on mental health have become central themes in scientific research. As the complexities of modern life continue to increase, understanding the factors that contribute to stress-related outcomes, particularly depression, has become a pressing concern. One factor that has gained significant interest is the concept of “unwholesome” consciousness, characterized by negative valence and a pessimistic worldview.</p>
<p>Unwholesome consciousness has been hypothesized to play a pivotal role in individuals’ susceptibility to stress-related mental health issues, particularly depression. This state of consciousness involves an inclination towards negative thoughts, feelings of hopelessness, and a tendency to perceive adverse situations more intensely. As a result, individuals with unwholesome consciousness may be more prone to experiencing the adverse effects of stress on their mental well-being.</p>
<p>The current study aims to explore the relationship between unwholesome consciousness and depression using data from the Nederlandse Verkorte MMPI (NVM) datamatrix. The investigation involves regression analysis to estimate odds ratios, quantifying the strength of association between consciousness and depression. The study also examines the distribution of behavior factors, such as negativism, somatization, shyness, psychopathology, and extraversion, based on consciousness categories to gain a more nuanced understanding of how consciousness operates in the broader context of stress-related outcomes.</p>
<p>The findings of this research hold the promise of contributing to the development of targeted interventions and strategies for stress management and mental well-being. By identifying the role of unwholesome consciousness in depression and its relationship to behavior factors, the study may inform interventions aimed at promoting more positive cognitive patterns and emotional well-being. Furthermore, exploring other personality traits and behavior factors in relation to consciousness can provide valuable insights into the diverse pathways through which stress manifests in individuals’ lives.</p>
</div>
<div id="methods" class="section level1">
<h1><strong>Methods</strong></h1>
<p><strong>Data Collection</strong>
The data used in this study is sourced from the NVM (Nederlandse Verkorte MMPI) datamatrix, a dataset containing information on various characteristics related to consciousness and stress. The dataset includes 188 rows and 11 columns, with details on age, gender, negativism, somatization, shyness, psychopathology, extraversion, and consciousness (categorized as neutral, unwholesome, or wholesome).</p>
<p><strong>NVM dataframe</strong></p>
<div id="olfbrazarx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#olfbrazarx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#olfbrazarx thead, #olfbrazarx tbody, #olfbrazarx tfoot, #olfbrazarx tr, #olfbrazarx td, #olfbrazarx th {
  border-style: none;
}

#olfbrazarx p {
  margin: 0;
  padding: 0;
}

#olfbrazarx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#olfbrazarx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#olfbrazarx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#olfbrazarx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#olfbrazarx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#olfbrazarx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#olfbrazarx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#olfbrazarx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#olfbrazarx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#olfbrazarx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#olfbrazarx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#olfbrazarx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#olfbrazarx .gt_spanner_row {
  border-bottom-style: hidden;
}

#olfbrazarx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#olfbrazarx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#olfbrazarx .gt_from_md > :first-child {
  margin-top: 0;
}

#olfbrazarx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#olfbrazarx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#olfbrazarx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#olfbrazarx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#olfbrazarx .gt_row_group_first td {
  border-top-width: 2px;
}

#olfbrazarx .gt_row_group_first th {
  border-top-width: 2px;
}

#olfbrazarx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#olfbrazarx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#olfbrazarx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#olfbrazarx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#olfbrazarx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#olfbrazarx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#olfbrazarx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#olfbrazarx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#olfbrazarx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#olfbrazarx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#olfbrazarx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#olfbrazarx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#olfbrazarx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#olfbrazarx .gt_left {
  text-align: left;
}

#olfbrazarx .gt_center {
  text-align: center;
}

#olfbrazarx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#olfbrazarx .gt_font_normal {
  font-weight: normal;
}

#olfbrazarx .gt_font_bold {
  font-weight: bold;
}

#olfbrazarx .gt_font_italic {
  font-style: italic;
}

#olfbrazarx .gt_super {
  font-size: 65%;
}

#olfbrazarx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#olfbrazarx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#olfbrazarx .gt_indent_1 {
  text-indent: 5px;
}

#olfbrazarx .gt_indent_2 {
  text-indent: 10px;
}

#olfbrazarx .gt_indent_3 {
  text-indent: 15px;
}

#olfbrazarx .gt_indent_4 {
  text-indent: 20px;
}

#olfbrazarx .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;N = 188&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>N = 188</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">gender</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Female</td>
<td headers="stat_0" class="gt_row gt_center">113 (60%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Male</td>
<td headers="stat_0" class="gt_row gt_center">75 (40%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">age</td>
<td headers="stat_0" class="gt_row gt_center">38 (28, 47)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">negativism</td>
<td headers="stat_0" class="gt_row gt_center">23 (18, 27)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">somatization</td>
<td headers="stat_0" class="gt_row gt_center">16 (10, 22)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">shyness</td>
<td headers="stat_0" class="gt_row gt_center">12 (6, 21)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">psychopathology</td>
<td headers="stat_0" class="gt_row gt_center">3.0 (2.0, 6.0)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">extraversion</td>
<td headers="stat_0" class="gt_row gt_center">15.0 (11.0, 18.0)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">consciousness</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    neutral</td>
<td headers="stat_0" class="gt_row gt_center">90 (48%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    unwholesome</td>
<td headers="stat_0" class="gt_row gt_center">53 (28%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    wholesome</td>
<td headers="stat_0" class="gt_row gt_center">45 (24%)</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> n (%); Median (IQR)</td>
    </tr>
  </tfoot>
</table>
</div>
<p><strong>Table 1</strong></p>
<pre><code>## # A tibble: 3 × 5
##   consciousness negativism somatization extraversion shyness
##   &lt;fct&gt;              &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;   &lt;dbl&gt;
## 1 wholesome           17.4         12           14.3    10.4
## 2 neutral             21.7         16.2         14.6    11.9
## 3 unwholesome         26.8         20.3         15      17.8</code></pre>
<p><strong>Data Visualization</strong>
To better visualize the relationship between consciousness and stress, two bar plots were created using the ggplot2 package in R. These plots display the distribution of consciousness categories (neutral, unwholesome, and wholesome) among the participants.</p>
<p><strong>Description of Results from Figures 1 and 2</strong></p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><strong>Figure 1: Consciousness and Stress</strong>
Figure 1 is a bar plot that visually represents the distribution of consciousness categories (neutral, unwholesome, and wholesome) among participants in the study. The visualization provides valuable insights into the prevalence of different consciousness levels in the population and their potential impact on stress experiences.</p>
<p><strong>Distribution of Consciousness Categories</strong>
The bar plot illustrates that the largest proportion of participants, approximately 48%, reported having a neutral consciousness. This suggests that a significant portion of the population does not exhibit strong tendencies towards either positive or negative valence in their cognitive patterns and worldview.</p>
<p>Approximately 28% of participants reported unwholesome consciousness, indicating a considerable number of individuals with a pessimistic and negative outlook. This finding highlights the prevalence of negative valence, which has been linked to stress-related mental health issues.</p>
<p>Around 24% of participants had wholesome consciousness, indicating a more positive and optimistic cognitive pattern. Wholesome consciousness is characterized by a healthier worldview and emotional well-being, which may contribute to reduced susceptibility to stress-related outcomes.</p>
<p>Behavior Factors Based on Consciousness Categories
The visualization also provides insights into behavior factors (negativism, somatization, shyness, psychopathology, and extraversion) based on the three consciousness categories.</p>
<p>Among participants with unwholesome consciousness, higher levels of negativism, somatization, shyness, psychopathology, and lower levels of extraversion were observed. This suggests that negative valence may be associated with higher levels of stress-related behaviors and emotional difficulties.</p>
<p>Participants with neutral and wholesome consciousness exhibited lower levels of negativism, somatization, shyness, and psychopathology, as well as higher levels of extraversion. This indicates a potential link between positive cognitive patterns and reduced stress-related behaviors and emotional challenges.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><strong>Figure 2: Consciousness and Stress by Gender</strong>
Figure 2 is a bar plot that displays the distribution of consciousness categories (neutral, unwholesome, and wholesome) among male and female participants. The visualization aims to investigate whether gender influences consciousness levels in relation to stress.</p>
<p><strong>Gender Distribution of Consciousness Categories</strong>
The bar plot shows a similar distribution of consciousness categories among both male and female participants. Approximately 48% of individuals from both genders reported having a neutral consciousness, while 28% had unwholesome consciousness, and 24% had wholesome consciousness.</p>
<p><strong>Implications and Interpretation</strong>
The similarity in consciousness distribution between genders suggests that gender may not be a significant factor influencing consciousness levels in relation to stress in this particular study. This implies that the relationship between unwholesome consciousness and stress, particularly depression, may be universal across both males and females.</p>
<p><strong>Overall Interpretation</strong>
The results from both Figure 1 and Figure 2 underscore the significance of consciousness in the context of stress-related outcomes. Unwholesome consciousness, characterized by negative valence and pessimistic thought patterns, is prevalent in the population and appears to be associated with higher levels of stress-related behaviors and emotional difficulties. This finding suggests that addressing negative valence and promoting positive cognitive patterns may be essential for stress management and mental well-being.</p>
<p>Moreover, the universality of the relationship between unwholesome consciousness and stress, as indicated by the consistent distribution across genders, highlights the relevance of this factor for diverse populations. These insights may inform the development of targeted interventions and strategies to mitigate the impact of negative valence on mental health outcomes and promote positive well-being and stress reduction.</p>
<p><strong>Regression Model</strong>
A regression analysis was performed to examine the association between consciousness and depression. The primary predictor variable was unwholesome consciousness, and extraversion and shyness were included as covariates. Odds ratios (OR) were calculated to determine the strength of association between the predictor variables and depression. Confidence intervals (CI) and p-values were used to assess the statistical significance of the results.</p>
<div id="cknjdbznjh" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#cknjdbznjh table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#cknjdbznjh thead, #cknjdbznjh tbody, #cknjdbznjh tfoot, #cknjdbznjh tr, #cknjdbznjh td, #cknjdbznjh th {
  border-style: none;
}

#cknjdbznjh p {
  margin: 0;
  padding: 0;
}

#cknjdbznjh .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: small;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cknjdbznjh .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#cknjdbznjh .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cknjdbznjh .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cknjdbznjh .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cknjdbznjh .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cknjdbznjh .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cknjdbznjh .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cknjdbznjh .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cknjdbznjh .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cknjdbznjh .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cknjdbznjh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cknjdbznjh .gt_spanner_row {
  border-bottom-style: hidden;
}

#cknjdbznjh .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#cknjdbznjh .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cknjdbznjh .gt_from_md > :first-child {
  margin-top: 0;
}

#cknjdbznjh .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cknjdbznjh .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cknjdbznjh .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cknjdbznjh .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cknjdbznjh .gt_row_group_first td {
  border-top-width: 2px;
}

#cknjdbznjh .gt_row_group_first th {
  border-top-width: 2px;
}

#cknjdbznjh .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cknjdbznjh .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cknjdbznjh .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cknjdbznjh .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cknjdbznjh .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cknjdbznjh .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cknjdbznjh .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#cknjdbznjh .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cknjdbznjh .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cknjdbznjh .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cknjdbznjh .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cknjdbznjh .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cknjdbznjh .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cknjdbznjh .gt_left {
  text-align: left;
}

#cknjdbznjh .gt_center {
  text-align: center;
}

#cknjdbznjh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cknjdbznjh .gt_font_normal {
  font-weight: normal;
}

#cknjdbznjh .gt_font_bold {
  font-weight: bold;
}

#cknjdbznjh .gt_font_italic {
  font-style: italic;
}

#cknjdbznjh .gt_super {
  font-size: 65%;
}

#cknjdbznjh .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#cknjdbznjh .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cknjdbznjh .gt_indent_1 {
  text-indent: 5px;
}

#cknjdbznjh .gt_indent_2 {
  text-indent: 10px;
}

#cknjdbznjh .gt_indent_3 {
  text-indent: 15px;
}

#cknjdbznjh .gt_indent_4 {
  text-indent: 20px;
}

#cknjdbznjh .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_title gt_font_normal" style>Table 2: Regression Analysis Results</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Unwholesome Consciousness, Extraversion and Shyness as predictors for Depression</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;exp(Beta)&lt;/strong&gt;"><strong>exp(Beta)</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">unwholesome</td>
<td headers="estimate" class="gt_row gt_center">1.29</td>
<td headers="ci" class="gt_row gt_center">1.17, 1.43</td>
<td headers="p.value" class="gt_row gt_center"><0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left gt_striped">extraversion</td>
<td headers="estimate" class="gt_row gt_center gt_striped">1.00</td>
<td headers="ci" class="gt_row gt_center gt_striped">0.99, 1.01</td>
<td headers="p.value" class="gt_row gt_center gt_striped">0.6</td></tr>
    <tr><td headers="label" class="gt_row gt_left">shyness</td>
<td headers="estimate" class="gt_row gt_center">1.00</td>
<td headers="ci" class="gt_row gt_center">1.00, 1.01</td>
<td headers="p.value" class="gt_row gt_center">0.7</td></tr>
    <tr><td headers="label" class="gt_row gt_left gt_striped" style="border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;">No. Obs.</td>
<td headers="estimate" class="gt_row gt_center gt_striped" style="border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;">188</td>
<td headers="ci" class="gt_row gt_center gt_striped" style="border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;"></td>
<td headers="p.value" class="gt_row gt_center gt_striped" style="border-top-width: 2px; border-top-style: solid; border-top-color: #D3D3D3;"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">Log-likelihood</td>
<td headers="estimate" class="gt_row gt_center">-34.9</td>
<td headers="ci" class="gt_row gt_center"></td>
<td headers="p.value" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left gt_striped">AIC</td>
<td headers="estimate" class="gt_row gt_center gt_striped">79.7</td>
<td headers="ci" class="gt_row gt_center gt_striped"></td>
<td headers="p.value" class="gt_row gt_center gt_striped"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">BIC</td>
<td headers="estimate" class="gt_row gt_center">95.9</td>
<td headers="ci" class="gt_row gt_center"></td>
<td headers="p.value" class="gt_row gt_center"></td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4">Source: https://github.com/EdwardHill15/Data</td>
    </tr>
    <tr>
      <td class="gt_sourcenote" colspan="4">Null deviance = 18.7; Null df = 187; Log-likelihood = -34.9; AIC = 79.7; BIC = 95.9; Deviance = 15.9; Residual df = 184; No. Obs. = 188</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="results" class="section level1">
<h1><strong>Results</strong></h1>
<p>The bar plot representing the distribution of consciousness categories illustrates that 48% of participants reported neutral consciousness, 28% reported unwholesome consciousness, and 24% reported wholesome consciousness. Additionally, the visualization explicitly shows the distribution of behavior factors based on consciousness categories. Among those with unwholesome consciousness, the median levels of negativism, somatization, shyness, psychopathology, and extraversion were 23, 16, 12, 3.0, and 15.0, respectively (with interquartile ranges indicated in parentheses). The visualization also highlights similar patterns for participants with neutral and wholesome consciousness.</p>
<p>The regression analysis results revealed that unwholesome consciousness was significantly associated with depression (OR = 1.29, 95% CI: 1.17 to 1.43, p &lt; 0.001). This suggests that individuals with unwholesome consciousness were 1.29 times more likely to experience depression compared to those with neutral consciousness. Conversely, extraversion (OR = 1.00, 95% CI: 0.99 to 1.01, p = 0.6) and shyness (OR = 1.00, 95% CI: 1.00 to 1.01, p = 0.7) showed weaker or non-significant associations with depression.</p>
<p>The odds ratio for Unwholesome Consciousness as a predictor for depression is 1.29 (95% CI 1.17, 1.43; p &lt; 0.001).</p>
<p>The odds ratio for Extraversion as a predictor for depression is 1.00 (95% CI 0.99, 1.01; p = 0.6).</p>
<p>The odds ratio for Shyness as a predictor for depression is 1.00 (95% CI 1.00, 1.01; p = 0.7).</p>
</div>
<div id="discussion" class="section level1">
<h1><strong>Discussion</strong></h1>
<p><strong>Interpretation of Visualization Results for Different Categories and Regression Analysis</strong>
The visualization results provided valuable insights into the distribution of consciousness categories among participants based on different categories, such as gender and behavior types. Additionally, the regression analysis offered further understanding of the relationship between consciousness and depression, along with the influence of other behavior factors. Let’s discuss these findings in detail:</p>
<p><strong>Interpretation by Gender</strong>
The visualization displayed the distribution of consciousness categories (neutral, unwholesome, and wholesome) among female and male participants. The results revealed that the proportion of individuals with each consciousness category was relatively similar for both genders. Around 48% of participants from each gender reported having a neutral consciousness, while 28% had unwholesome consciousness, and 24% had wholesome consciousness.</p>
<p>The similarity in the distribution of consciousness categories between genders implies that gender may not play a significant role in determining consciousness levels. This suggests that the impact of consciousness on stress might not be strongly influenced by gender in this study.</p>
<p><strong>Interpretation by Behavior Types</strong>
The visualization also showed the distribution of behavior factors (negativism, somatization, shyness, and extraversion) based on the three categories of wholesome, neutral and unwholesome consciousness. These behavior factors are important elements that may contribute to understanding the relationship between consciousness and stress.</p>
<p>To better interpret the results, further analysis is needed to explore how consciousness levels are associated with different behavior types. For instance, it would be insightful to examine whether individuals with unwholesome consciousness exhibit higher levels of negativism or somatization compared to those with neutral or wholesome consciousness. Understanding the connection between consciousness and behavior factors could provide valuable insights into how negative valence affects stress-related behaviors.</p>
<p><strong>Regression Analysis Results</strong>
The regression analysis aimed to explore the association between consciousness and depression, considering extraversion and shyness as covariates. The results indicated that unwholesome consciousness was significantly associated with depression, as evidenced by an odds ratio (OR) of 1.29 (95% CI: 1.17 to 1.43, p &lt; 0.001).</p>
<p>This finding suggests that individuals with unwholesome consciousness were 1.29 times more likely to experience depression compared to those with neutral consciousness. This highlights the importance of negative valence and its potential impact on mental health, particularly in relation to depression.</p>
<p>However, extraversion and shyness did not show a significant association with depression, as evidenced by their ORs close to 1 and p-values greater than 0.05. This implies that, in this study, extraversion and shyness might not be strong predictors of depression or stress-related outcomes.</p>
<p><strong>Integrating Results</strong>
Integrating the results of the visualization and regression analysis, we can infer that unwholesome consciousness is a significant predictor of depression, independent of gender. This indicates that individuals with unwholesome consciousness may be more susceptible to experiencing stress-related mental health issues, particularly depression.</p>
<p>However, the lack of a significant relationship between extraversion and shyness with depression suggests that these personality traits might not have a substantial impact on depression or stress in this particular study.</p>
</div>
<div id="limitations-and-future-directions" class="section level1">
<h1><strong>Limitations and Future Directions</strong></h1>
<p>It is essential to recognize the limitations of this study. The data collected from the NVM datamatrix might have its specific context and constraints, limiting the generalizability of the findings. Additionally, the cross-sectional nature of the data prevents us from establishing causal relationships between consciousness, behavior types, and depression.</p>
<p>For future research, longitudinal studies could provide deeper insights into the temporal dynamics of consciousness, behavior factors, and mental health outcomes. Additionally, exploring the interplay between different behavior factors and consciousness may help identify specific pathways through which negative valence influences stress-related behaviors and mental health.</p>
<p>The results of this study provide valuable insights into the relationship between consciousness and stress-related outcomes, with a particular emphasis on depression. The visualization of consciousness categories among participants reveals that a substantial proportion reported unwholesome consciousness, indicating the prevalence of negative valence in the population under study. This finding aligns with previous research suggesting that negative thought patterns and pessimistic worldviews are prevalent risk factors for stress-related mental health issues.</p>
<p>Moreover, the distribution of behavior factors based on consciousness categories sheds light on the interplay between consciousness and stress. The higher levels of negativism, somatization, shyness, and psychopathology observed among individuals with unwholesome consciousness suggest that negative valence may contribute to the amplification of stress experiences. Understanding these associations can inform targeted interventions to address specific behavior patterns and cognitive processes in individuals with unwholesome consciousness, ultimately promoting mental well-being and stress reduction.</p>
<p>The regression analysis results further support the significance of unwholesome consciousness as a predictor of depression. The odds ratio of 1.29 indicates a moderate effect size, indicating that unwholesome consciousness is a meaningful factor in susceptibility to depression. This finding underscores the importance of negative valence in stress-related mental health outcomes and highlights the need for interventions targeting consciousness to mitigate the risk of depression.</p>
<p>Interestingly, the lack of a significant association between extraversion and shyness with depression suggests that these personality traits might not play a significant role in depression in the context of this study. However, it is crucial to consider that personality traits are complex and multifaceted, and their influence on mental health outcomes may vary across different populations and contexts.</p>
<p>The gender analysis revealed a consistent distribution of consciousness categories among male and female participants, implying that gender may not be a strong determinant of consciousness levels in relation to stress. This suggests that the relationship between unwholesome consciousness and depression is universal across genders. However, it is essential to note that gender-related factors may still influence stress and mental health outcomes in other ways that were not directly addressed in this study.</p>
<p>The study’s limitations should be acknowledged. The cross-sectional nature of the data prevents us from establishing causality between consciousness and depression, and further longitudinal research is needed to explore the temporal dynamics of these relationships. Additionally, the data’s source from the NVM datamatrix may have its specific context and constraints, limiting the generalizability of the findings to other populations.</p>
<p>Future research endeavors may include examining the longitudinal associations between consciousness and stress-related outcomes, as well as investigating the potential moderating or mediating effects of other psychosocial and environmental factors. Additionally, considering cultural and contextual differences in the relationship between consciousness and stress could provide valuable insights into the universality of these findings.</p>
</div>
<div id="conclusion" class="section level1">
<h1><strong>Conclusion</strong></h1>
<p>This study contributes to our understanding of the complex interplay between consciousness and stress-related mental health outcomes, particularly depression. Unwholesome consciousness emerged as a significant predictor of depression, highlighting the importance of negative valence in mental well-being. The insights gained from this research may inform the development of targeted interventions and strategies to promote positive cognitive patterns and emotional well-being, ultimately contributing to stress management and improved mental health. By addressing unwholesome consciousness, healthcare professionals and policymakers can work towards more effective approaches to mental health interventions and overall well-being. Further exploration of consciousness and its relation to stress in diverse populations will advance our knowledge and pave the way for evidence-based strategies to combat stress-related mental health challenges.</p>
</div>
